"Resource/OptionsSubGyro.res"
{
	"ClientModGyroMenu"
	{
		"ControlName"		"ClientModGyroMenu"
		"fieldName"		"ClientModGyroMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"GyroEnableCheckBox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"GyroEnableCheckBox"
		"xpos"			"10"
		"ypos"			"16"
		"wide"			"280"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_Enable"
		"textAlignment"		"west"
	}
	
	"GyroPitchSensitivityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GyroPitchSensitivityLabel"
		"xpos"			"300"
		"ypos"			"16"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_PitchSensitivity"
		"textAlignment"		"west"
	}
	"GyroReversePitchCheckBox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"GyroReversePitchCheckBox"
		"xpos"			"10"
		"ypos"			"46"
		"wide"			"280"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_ReversePitch"
		"textAlignment"		"west"
	}
	"GyroReverseYawCheckBox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"GyroReverseYawCheckBox"
		"xpos"			"10"
		"ypos"			"76"
		"wide"			"280"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_ReverseYaw"
		"textAlignment"		"west"
	}

	"GyroPitchSensitivityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GyroPitchSensitivityLabel"
		"xpos"			"300"
		"ypos"			"16"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_PitchSensitivity"
		"textAlignment"		"west"
	}
	"GyroPitchSensitivitySlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"GyroPitchSensitivitySlider"
		"xpos"			"300"
		"ypos"			"40"
		"wide"			"180"
		"tall"			"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"leftText"		"0"
		"rightText"		"2"
	}

	"GyroYawSensitivityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GyroYawSensitivityLabel"
		"xpos"			"300"
		"ypos"			"90"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_YawSensitivity"
		"textAlignment"		"west"
	}
	"GyroYawSensitivitySlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"GyroYawSensitivitySlider"
		"xpos"			"300"
		"ypos"			"114"
		"wide"			"180"
		"tall"			"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"leftText"		"0"
		"rightText"		"2"
	}

	"GyroDeadzoneLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GyroDeadzoneLabel"
		"xpos"			"300"
		"ypos"			"164"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_Deadzone"
		"textAlignment"		"west"
	}
	"GyroDeadzoneSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"GyroDeadzoneSlider"
		"xpos"			"300"
		"ypos"			"188"
		"wide"			"180"
		"tall"			"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"leftText"		"0"
		"rightText"		"3"
	}
	
	"GyroScopedSensitivityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GyroScopedSensitivityLabel"
		"xpos"			"16"
		"ypos"			"110"
		"wide"			"180"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#GameUI_Gyro_ScopedSensitivity"
		"textAlignment"		"west"
	}
	"GyroScopedSensitivitySlider"
	{
		"ControlName"   "CCvarSlider"
		"fieldName"     "GyroScopedSensitivitySlider"
		"xpos"          "16"
		"ypos"          "135"
		"wide"          "180"
		"tall"          "40"
		"autoResize"    "0"
		"pinCorner"     "0"
		"visible"       "1"
		"enabled"       "1"
	}
}
